# Generated by Django 4.1.5 on 2023-01-27 11:55

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_enum.fields.EnumCharField(choices=[('J', 'Junior'), ('J+', 'Junior+'), ('M', 'Middle'), ('M+', 'Middle+'), ('S', 'Senior')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor_app.grade'),
        ),
    ]
