# Generated by Django 4.1.5 on 2023-01-27 12:01

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0003_alter_user_grade_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=django_enum.fields.EnumCharField(choices=[('N', 'None'), ('J', 'Junior'), ('J+', 'Junior+'), ('M', 'Middle'), ('M+', 'Middle+'), ('S', 'Senior')], default=None, max_length=2, null=True),
        ),
    ]
