# Generated by Django 4.1.5 on 2023-01-27 12:38

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0004_alter_user_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=django_enum.fields.EnumCharField(choices=[('Junior', 'Junior'), ('Junior+', 'Junior Plus'), ('Middle', 'Middle'), ('Middle+', 'Middle Plus'), ('Senior', 'Senior')], default=None, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', django_enum.fields.EnumCharField(choices=[('Junior', 'Junior'), ('Junior+', 'Junior Plus'), ('Middle', 'Middle'), ('Middle+', 'Middle Plus'), ('Senior', 'Senior')], default=None, max_length=7, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mentor_app.area')),
            ],
        ),
    ]
