# Generated by Django 4.1.5 on 2023-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_app', '0005_area_alter_user_grade_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
